---
- name: install java-1.8.0-openjdk-devel
  yum: >
    name=java-1.8.0-openjdk-devel
    state=present
- name: import rpm key
  rpm_key: >
    state=present
    key=https://packages.elastic.co/GPG-KEY-elasticsearch
- name: Put /etc/yum.repos.d/elasticsearch.repo
  copy: >
    src=elasticsearch.repo
    dest=/etc/yum.repos.d/elasticsearch.repo
    owner=root
    group=root
    mode=0644
- name: install elasticsearch
  yum: >
    name=elasticsearch
    state=present
  notify: restart elasticsearch
- name: Update /etc/sysconfig/elasticsearch
  lineinfile: >
    dest=/etc/sysconfig/elasticsearch
    regexp='^JAVA_HOME='
    line='JAVA_HOME=/usr/lib/jvm/jre-1.8.0' 
  notify: restart elasticsearch
- name: reload systemd
  command: /usr/bin/systemctl daemon-reload
- name: enable elasticsearch
  service: >
    name=elasticsearch
    enabled=yes
